### PR TITLE
Mouse gene list and bug fixes

### PR DESCRIPTION
**Pull request by yhwu**
1. Added mouse onco gene list.
2. bug fix for sites.multi
3. fix bug in getAbundanceThreshold

### CODE REVIEW

**Comment by anatolydryga** [comment]
@cnobles could you review this pull request and merge it if it OK with you.

**Comment by cnobles** [comment]
MECOM doesn't exist in the murine cancer list but it's still included in the report with the other bad actors (LMO2, CCND2, HMGA2, and IKZF1). It seems to exist in the Mus musculus genome and should be caught (?) if searching for the MECOM gene in the bad actors section (line 315: DETAILED REPORTS FOR BAD ACTORS). I just want to point this out.

Options: we leave as is, and if we get anything interesting in MECOM, it would get reported in that section, but MECOM would not be reported as an onco-gene (~, right?) but it would get "!". We could manually add MECOM to the murine onco-list, then integration events in that gene would be reported with the "~!" designation, like it would in a human patient report.

Thoughts?

**Comment by cnobles** [comment]
I get an error when trying to get the patient info from the specimen management db. I ran it with old code, no problem. New code runs into error on both PMACS and microb120. Error message below:

Rscript ../../scripts/geneTherapyPatientReportMaker/check_patient_gtsp.R pMouseCulture
Error in .local(drv, ...) :
  Failed to connect to database: Error: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
Calls: dbConnect -> .valueClassTest -> is -> is -> .local -> .Call
Execution halted

**Comment by cnobles** [comment]
Looks like everything is working well! Just have to remember to throw the ref genome flag.

**Pull request merged**
